"""Manuscript prose and figure legends tied to the publication output schema.

Values are inserted at build time; paragraphs outside these replacements retain
source text and native Word equations in the document builder.
"""
MAIN_CAPTIONS = {
1: ('Cultural location and cultural prompting. (a) The release-updated human cultural map uses Tao et al.’s eight region colours (1); red symbols locate the unconditioned models. All 107 countries and three models are labelled. (b) Paired Euclidean distances from unconditioned and country-conditioned expected-score positions to the same human countries. Pink/purple denotes no cultural prompting; blue denotes cultural prompting. Boxes show interquartile ranges, centre lines medians, whiskers observations within 1.5 interquartile ranges, and dots more extreme observations. White diamonds mark means. Annotations give mean distance changes and percentages improved. GPT-4o and Jev use 107 countries; Sol uses 91. These estimates extend the original point-response design. The external Tao benchmark and variant-wise modal reconstruction are reported separately in Table S16.'),
2: ('Information retained by full response distributions. Mean Jensen-Shannon divergence (JSD) between each model and human response frequencies is shown for the full probability vector (blue circles) and the deterministic argmax of that same aggregated vector (pink/purple squares). Lines connect the paired representations within each model. Right-hand columns report the mean argmax-minus-full difference, the fraction of country-item cells with strictly lower JSD under the full representation, and the number of paired cells. Means are descriptive and use each model’s observed coverage; no additional model responses are sampled.'),
3: ('Population specificity of model probabilities. (a) Mean country-conditioning gain, defined as JSD from the same model’s unconditioned distribution minus JSD from its country-conditioned distribution. Positive values indicate improved fidelity to the target human distribution. Bars show 95% percentile intervals from 5,000 crossed country-by-item bootstrap replicates; annotations show the fraction of observed cells improved. (b) Country-conditioned model JSD compared with an equal-country human distribution constructed from all other countries for that item, leaving out the target country (LOCO). Each human benchmark is averaged on the corresponding model’s observed cells. Annotations show the fraction of cells in which the model beats LOCO and the cell count. Colours identify GPT-4o (blue), Sol (orange), and Jev (green).'),
4: ('Average disagreement and the structure of disagreement. (a) Mean normalized entropy of each model and of the human distributions on the same observed cells. Right-hand values report model / human means. (b) Slopes from regressions of model entropy on human entropy: pooled, with item fixed effects, and with both country and item fixed effects. Error bars are asymptotic 95% normal intervals using two-way cluster-robust covariance by country and item. The dashed line marks zero association and the dotted line marks a unit slope. There are only nine item clusters, so these intervals should be interpreted cautiously. Sample sizes are 963 cells for GPT-4o and Jev and 946 for Sol. A slope below one is not itself evidence that the model’s cross-cell entropy variance is smaller than the human variance; Table S10 reports both quantities.'),
}
MAIN_FIGURES=['figure1_tao_replication','figure2_probability_value','figure3_population_specificity','figure4_heterogeneity_structure']
SI_FIGURES=[
('figure_s1_sol_vs_jev_fidelity','Paired distributional fidelity. Each point is one of 946 country-item cells observed for both Sol and Jev. Axes show JSD from the same human distribution. Points below the equality line favour Jev; points above favour Sol. Points are partially transparent to show density.'),
('figure_s2_prompt_sensitivity','Respondent-wording sensitivity. Empirical cumulative distributions of JSD between each retained descriptor-specific vector and its model-country-item mean. Label assignments are averaged within descriptor before comparison. The unconditioned target is excluded. Cells with fewer than two retained descriptors have undefined sensitivity and do not contribute; retained comparison counts appear in the legend. The full observed range is displayed.'),
('figure_s3_label_sensitivity_heatmap','Response-label sensitivity. Mean JSD between each retained OpenAI label assignment and its within-descriptor mean, after remapping labels to substantive responses. The unconditioned target is excluded. At least two label assignments must survive the primary censoring policy; singletons are treated as unavailable, not zero sensitivity. Parentheses give the number of retained label-vector comparisons. The near-zero Sol values are conditional on the surviving comparisons.'),
('figure_s4_option_order_heatmap','Option-order sensitivity. Mean JSD between alternative answer orderings and the prespecified reference ordering, rep=0, after substantive remapping. Both requests must survive the primary censoring policy. Parentheses show comparison counts; up to three comparisons are available per country-item cell in the 12-country experiment. Sol has no valid reference-based F120 comparisons, shown as NA. A later retained ordering is never substituted for an excluded reference.'),
('figure_s5_item_error_heatmap','Distributional error by item. Mean country-conditioned JSD from human response frequencies, with the number of countries shown in parentheses. The colour scale spans the theoretical JSD range from zero to one. All available cells enter each model’s mean; cross-model inferential comparisons use matched cells.'),
('figure_s6_topk_retention','OpenAI probability-recovery coverage. Percentage of all 37,800 primary requests per OpenAI condition retained under the primary omitted-mass bound of 0.001, the stricter bound of 0.0001, and the requirement that every permitted label be observed. Counts include the unconditioned target and Y003 constituent requests. Retention is evaluated at the request level before averaging probabilities.'),
('figure_s7_y003_mae','Fidelity of the four autonomy-index marginals. Mean absolute error between predicted and human selection probabilities for each constituent, averaged across 107 countries per model. These are four marginal probabilities; the analysis does not reconstruct the joint distribution of selections or assume independence.'),
('figure_s8_cultural_map_representations','Cultural-map distance under alternative probability representations. Blue uses expected scores from averaged probabilities; pink/purple uses the argmax of the final averaged probabilities; gold averages projected modal profiles across complete prompt variants. Boxes, whiskers, and outliers follow the convention in Figure 1. Sample sizes are shown below each box. The variant-wise modal reconstruction yields only 43 country-conditioned Sol profiles and no complete unconditioned Sol profile. Its distribution therefore has different coverage and cannot support the paired prompting comparison. Common-country expected-score and aggregated-argmax results appear in Table S15.'),
('figure_s9_entropy_by_item_heatmap','Within-item entropy association. Pearson correlations between model and human normalized entropy across countries for each survey item. The fixed colour scale spans -1 to 1; parentheses give country counts. These descriptive associations distinguish variation across countries within a question from pooled differences across questions.'),
('figure_s10_population_specificity_by_item_heatmap','Country-conditioning gain by item. Mean JSD from the unconditioned model minus mean JSD from the country-conditioned model, evaluated against the same target-country human distribution. Blue denotes improvement and red denotes deterioration; the colour scale is symmetric around zero. Parentheses show country counts. Values are descriptive item-specific means.'),
('figure_s11_entropy_scatter_diagnostic','Raw entropy diagnostic. Each panel plots model normalized entropy against human normalized entropy for every observed country-item cell, with identical axes across models. The dashed line denotes exact entropy equality. Facets separate overlapping model clouds; pooled and fixed-effect associations are summarized in Figure 4 and Table S10.'),
]


def revised_results(d):
    """Return heading/text blocks with audited values supplied by the builder."""
    v=d
    return [
('h1','Results'),
('h2','Analysis coverage and probability recovery'),
('p','The merged EVS/WVS file contained 666,907 historical observations. Restricting the benchmark to common waves 5–7 and calendar years 2005–2022 retained 392,832 respondent records. Harmonization identified 112 countries and territories before the five source-study exclusions, leaving 107 analysis targets and 963 possible country-item cells across the nine primary constructs. The run used WVS Trend v4.1 and EVS ZA7503 v3.0.0. It is a release-updated replication and extension of Tao et al. (1), whose earlier release yielded 393,536 observations.'),
('p','GPT-4o returned every permitted label in 35,754 of 37,800 primary requests (94.6%); Sol did so in 1,922 requests (5.1%). The primary rule retained complete vectors and incomplete vectors whose unseen permitted-label mass was bounded above by 0.001. This retained 37,800 GPT-4o requests and 24,723 Sol requests (65.4%), yielding 963 and 946 country-item distributions, respectively. Jev supplied probabilities for every declared alternative; its 10,800 primary requests covered all 963 country-item cells and the autonomy marginals. Coverage and censoring diagnostics are reported in Tables S3 and S4.'),
('h2','Cultural prompting improves mean cultural location'),
('p',f"The unconditioned models occupy distinct positions in the human cultural map (Fig. 1a). Country prompting reduces mean expected-score distance from {v['map_u_gpt4o_anchor']:.3f} to {v['map_c_gpt4o_anchor']:.3f} for GPT-4o, from {v['map_u_gpt56_sol']:.3f} to {v['map_c_gpt56_sol']:.3f} for Sol, and from {v['map_u_jev']:.3f} to {v['map_c_jev']:.3f} for Jev (Fig. 1b). Distances improve for {v['map_pct_gpt4o_anchor']:.1f}%, {v['map_pct_gpt56_sol']:.1f}%, and {v['map_pct_jev']:.1f}% of observed countries, respectively. GPT-4o and Jev use 107 countries; Sol uses the 91 countries with complete ten-construct inputs. Within-model prompting comparisons use the same countries on both sides."),
('p','Tao et al. reported a GPT-4o mean distance reduction from 2.42 to 1.57 and improvement in 71.0% of countries (1). The current expected-score analysis changes both the response representation and the human-data release, so numerical proximity does not establish exact reproduction. A closer reconstruction that averages projected modal responses across prompt variants yields 2.380 to 1.603 for GPT-4o, with improvement in 74.8% of countries (Table S16). It still differs from the original temperature-zero, direct-response protocol, including its treatment of Y003. Sol lacks a complete unconditioned profile for this variant-wise modal reconstruction; its available country-conditioned modal profiles are reported only as a coverage-limited diagnostic (Fig. S8).'),
('p','Retaining probabilities also improves mean cultural alignment relative to taking the argmax of the final averaged vector: country-conditioned mean distance falls from 1.690 to 1.562 for GPT-4o, from 1.884 to 1.786 for Sol, and from 1.845 to 1.628 for Jev. On the common 91-country subset, expected-score distances are 1.545, 1.786, and 1.631, respectively (Table S15). These comparisons concern compressed cultural coordinates; they do not establish recovery of the underlying response distributions.'),
('h2','Full probabilities preserve information lost by modal answers'),
('p',f"Mean JSD from human response frequencies is {v['js_gpt4o_anchor']:.3f} for GPT-4o, {v['js_gpt56_sol']:.3f} for Sol, and {v['js_jev']:.3f} for Jev (Table 2). On the 946 cells shared by Sol and Jev, the mean Sol-minus-Jev difference is {v['sj_mean']:.3f} (95% crossed-bootstrap CI {v['sj_lo']:.3f} to {v['sj_hi']:.3f}). Mean total variation differs by 0.063 (0.008 to 0.117). The normalized Wasserstein contrast is 0.055, with an interval narrowly including zero (-0.0004 to 0.113). The paired diagnostic appears in Figure S1."),
('p','GPT-4o and Jev are less clearly separated. Their mean JSD difference is 0.020 across 963 matched cells (95% CI -0.016 to 0.053), and GPT-4o has lower mean total variation (0.379 versus 0.391). On the 946 cells shared by GPT-4o and Sol, GPT-4o has lower JSD by 0.079 on average (GPT-4o-minus-Sol 95% CI -0.113 to -0.045). These results describe the evaluated model snapshots and do not establish a general ordering of providers or interfaces.'),
('p',f"Collapsing each aggregated vector to its argmax increases mean JSD to {v['arg_gpt4o_anchor']:.3f}, {v['arg_gpt56_sol']:.3f}, and {v['arg_jev']:.3f}, respectively. The paired mean reductions from retaining the full distribution are {v['diff_gpt4o_anchor']:.3f}, {v['diff_gpt56_sol']:.3f}, and {v['diff_jev']:.3f}; the full distribution is closer in {v['better_gpt4o_anchor']:.1f}%, {v['better_gpt56_sol']:.1f}%, and {v['better_jev']:.1f}% of cells (Fig. 2; Table S5). This is a comparison of two representations of the same vector, without an additional API request. Nonmodal probability mass therefore contributes information about human response frequencies, although the gain is not uniform across cells."),
('p','Fidelity varies substantially by item (Fig. S5; Table S6). For justifiability of homosexuality (F118), mean JSD is 0.407 for GPT-4o, 0.518 for Sol, and 0.306 for Jev; for the post-materialist index (Y002), the values are 0.109, 0.244, and 0.068. Respect for authority (E018) shows smaller differences, at 0.175, 0.170, and 0.143. Country-level summaries are reported in Table S7.'),
('h2','Country information adds uneven population-specific information'),
('p',f"Improvement in cultural-map location does not imply improvement in every response distribution. Relative to the same model’s unconditioned distribution, mean country-conditioning JSD gain is {v['gain_gpt4o_anchor']:.3f} for GPT-4o (95% CI {v['gain_lo_gpt4o_anchor']:.3f} to {v['gain_hi_gpt4o_anchor']:.3f}), {v['gain_gpt56_sol']:.3f} for Sol ({v['gain_lo_gpt56_sol']:.3f} to {v['gain_hi_gpt56_sol']:.3f}), and {v['gain_jev']:.3f} for Jev ({v['gain_lo_jev']:.3f} to {v['gain_hi_jev']:.3f}). Country conditioning improves {v['gain_pct_gpt4o_anchor']:.1f}%, {v['gain_pct_gpt56_sol']:.1f}%, and {v['gain_pct_jev']:.1f}% of cells, respectively (Fig. 3a; Table 3). The GPT-4o interval includes zero, and fewer than half its cells improve despite a positive mean gain."),
('p',f"A simple human benchmark remains substantially closer to the target distributions. The equal-country average of all other countries for the same item, excluding the target country, has mean JSD approximately 0.052 on each model’s observed cells. The country-conditioned models beat this leave-one-country-out benchmark in only {v['loco_pct_gpt4o_anchor']:.1f}%, {v['loco_pct_gpt56_sol']:.1f}%, and {v['loco_pct_jev']:.1f}% of cells (Fig. 3b). Country prompts therefore add useful information relative to a model’s own default without recovering most of the distributional information already contained in this cross-national human baseline."),
('p','The item pattern further qualifies the mean gains (Fig. S10; Table S12). Country prompting worsens happiness-distribution fidelity for all three systems. Gains are particularly large for Sol on importance of God (0.524 JSD units) and for GPT-4o on justifiability of homosexuality (0.365). Such differences explain why a positive overall gain can coexist with deterioration across many country-item cells.'),
('h2','Average entropy and the pattern of disagreement remain distinct'),
('p','Across the full human benchmark, mean normalized entropy is 0.721. Model means are 0.378 for GPT-4o, 0.215 for Sol, and 0.657 for Jev; the human mean on Sol’s 946 observed cells is 0.718 (Fig. 4a). Mean absolute entropy errors are 0.372, 0.512, and 0.230, respectively. Jev thus comes closest to the average amount of human disagreement, while both GPT models produce more concentrated response distributions.'),
('p','The pooled slopes of model entropy on human entropy are 0.596 for GPT-4o (two-way cluster-robust 95% CI 0.235 to 0.958), 0.361 for Sol (0.150 to 0.571), and -0.010 for Jev (-0.177 to 0.156). With item fixed effects, the slopes are 0.456 (0.106 to 0.807), 0.297 (0.028 to 0.566), and -0.002 (-0.084 to 0.079). With both country and item fixed effects, they are 0.295 (-0.100 to 0.690), 0.258 (-0.020 to 0.536), and 0.013 (-0.119 to 0.144); all three intervals include zero (Fig. 4b; Table S10). The GPT models’ pooled positive associations therefore provide weaker evidence of tracking disagreement once both sources of structure are removed. Inference is approximate because the covariance estimator has only nine item clusters.'),
('p','Within-item correlations vary in sign and magnitude (Fig. S9; Table S11). For example, both GPT models show correlations near 0.78 for importance of God, while their correlations are negative for justifiability of homosexuality. Jev has a correlation of approximately -0.50 for abortion. Lower mean entropy and a slope below one should not be conflated with smaller cross-cell entropy variance: the model-to-human standard-deviation ratios are 1.446 for GPT-4o, 1.267 for Sol, and 1.013 for Jev (Table S10). These diagnostics distinguish the level, association, and variability of model uncertainty.'),
('h2','Sensitivity to elicitation and probability recovery'),
('p',f"Among country-conditioned cells with at least two retained descriptor variants, mean JSD from the model-country-item mean is {v['prompt_gpt4o_anchor']:.3f} for GPT-4o, {v['prompt_gpt56_sol']:.3f} for Sol, and {v['prompt_jev']:.3f} for Jev (Fig. S2; Table S8). Among descriptor groups with at least two retained label assignments, mean semantic label sensitivity is {v['label_gpt4o_anchor']:.3f} and {v['label_gpt56_sol']:.3f}, respectively (Fig. S3; Table S13). Groups with only one retained repetition cannot identify sensitivity and are treated as unavailable."),
('p',f"Comparing alternative option orders only with the prespecified reference order gives mean JSD {v['order_gpt4o_anchor']:.3f} for GPT-4o across 324 comparisons, {v['order_gpt56_sol']:.3f} for Sol across 157, and {v['order_jev']:.3f} for Jev across 324 (Fig. S4; Table S14). Sol has no valid reference-based F120 comparisons after censoring. Its smaller sensitivity estimate is conditional on selective retention and should not be interpreted as evidence of general invariance to order."),
('p','Tightening the unseen-mass bound from 0.001 to 0.0001 changes Sol’s mean JSD from 0.290 on 946 cells to 0.283 on 875 cells. Requiring every permitted label to be observed leaves only 101 cells, with mean JSD 0.161 (Fig. S6; Table S4). Because both retained requests and cell coverage change, this contrast cannot distinguish a censoring-policy effect from selection into the retained sample.'),
('p','Y003 was evaluated separately through the four marginal selection probabilities that determine the autonomy index. Mean absolute error across these marginals is 0.416 for GPT-4o, 0.384 for Sol, and 0.223 for Jev. Jev has the lowest mean error for each constituent (Fig. S7; Table S9). These results concern marginal probabilities and do not establish recovery of the joint pattern of child-rearing values.'),
]
